# Site Settings
title: VANS Pro Audio Rentals
description: Affordable professional quality audio for your events.
url: "https://www.vproaudio.rentals"
baseurl: "/"
author: "Vans"
email: "bookings@vproaudio.rentals"

year: 2025
company: "VANS Professional Audio Rentals"

plugins:
  - jekyll-seo-tag

seo:
  title: "VANS Pro Audio Rentals"
  description: "Affordable professional quality audio for your events."
  url: "https://www.vproaudio.rentals"
  image: "/assets/images/home1.jpg"


collections:
  faqs:
    output: false
  systems:
    output: true 
    permalink: /packages/:name/ 
  microphones:
    output: true 
    permalink: /packages/microphones/:name/ 
  instruments:
    output: true 
    permalink: /packages/musical-instruments/:name/ 
  lighting:
    output: true 
    permalink: /packages/party-lights/:name/ 
  power:
    output: true 
    permalink: /packages/outdoor-power/:name/ 