# Site Settings
title: VANS Pro Audio Rentals
description: Affordable, professional quality audio for your events.
url: "https://www.vproaudio.rentals"
baseurl: ""
author: "Edwin Vans"
email: "bookings@vproaudio.rentals"
lang: "en"
timezone: "America/Los_Angeles"
branding: "V Pro Audio"

year: 2025
company: "VANS Professional Audio Rentals"

plugins:
  - jekyll-seo-tag

seo:
  title: "VANS Pro Audio Rentals"
  description: "Affordable, professional quality audio for your events."
  url: "https://www.vproaudio.rentals"
  image: "/assets/images/home.jpg"

social:
  name: "VANS Pro Audio Rentals"
  links:
    - "https://www.tiktok.com/@vproaudiorentals"

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

sass:
  load_paths:
    - node_modules
  style: compressed

collections:
  faqs:
    output: false
  packages:
    output: true
    permalink: /packages/:name/

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
      image: "/assets/images/home.jpg"
      author: "Edwin Vans"
